kind = "web"
previewPath = "/"
title = "Viorelvar Market"
version = "1.0.0"
id = "artifacts/viorelvar-market"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24980

[services.development]
run = "pnpm --filter @workspace/viorelvar-market run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/viorelvar-market", "run", "build" ]
publicDir = "artifacts/viorelvar-market/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24980"
BASE_PATH = "/"
